[package]
authors = [
  "The Real-Time Interrupt-driven Concurrency developers",
  "Emil Fresk <emil.fresk@gmail.com>",
  "Henrik Tjäder <henrik@tjaders.com>",
  "Jorge Aparicio <jorge@japaric.io>",
  "Per Lindgren <per.lindgren@ltu.se>",
]
categories = ["concurrency", "embedded", "no-std", "asynchronous"]
description = "Real-Time Interrupt-driven Concurrency (RTIC): a concurrency framework for building real-time systems"
documentation = "https://rtic.rs/"
edition = "2021"
keywords = ["arm", "cortex-m", "risc-v", "embedded", "async", "runtime", "futures", "await", "no-std", "rtos", "bare-metal"]
license = "MIT OR Apache-2.0"
name = "rtic"
readme = "README.md"
repository = "https://github.com/rtic-rs/rtic"

version = "2.0.0-alpha.0"

[lib]
name = "rtic"

[dependencies]
cortex-m = "0.7.0"
rtic-macros = { path = "macros", version = "2.0.0-alpha.0" }
rtic-monotonic = "1.0.0"
rtic-core = "1.0.0"
heapless = "0.7.7"
bare-metal = "1.0.0"
#portable-atomic = { version = "0.3.19" }
atomic-polyfill = "1"

[build-dependencies]
version_check = "0.9"

[dev-dependencies]
lm3s6965 = "0.1.3"
cortex-m-semihosting = "0.5.0"
systick-monotonic = "1.0.0"

[dev-dependencies.panic-semihosting]
features = ["exit"]
version = "0.6.0"

[target.x86_64-unknown-linux-gnu.dev-dependencies]
trybuild = "1"

[profile.release]
codegen-units = 1
lto = true

[workspace]
members = ["macros", "xtask"]

# do not optimize proc-macro deps or build scripts
[profile.dev.build-override]
codegen-units = 16
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false


[profile.release.build-override]
codegen-units = 16
debug = false
debug-assertions = false
opt-level = 0
overflow-checks = false

[patch.crates-io]
lm3s6965 = { git = "https://github.com/japaric/lm3s6965" }

[features]
test-critical-section = ["cortex-m/critical-section-single-core"]

# [[example]]
# name = "pool"
# required-features = ["test-critical-section"]
