[package]
name = "rtic-timer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.6"
rtic-monotonic = "1.0.0"
fugit = "0.3.6"